require 'net/http'
require 'optparse'
require './lib/page_performance'
require './lib/page_performance/base/run'
require './lib/page_performance/error/error'
require './lib/page_performance/utils/prerequisites'
require './lib/page_performance/utils/argv_parser'
require './lib/page_performance/utils/tag_scanner'
require './lib/page_performance/output/writer'
require './lib/page_performance/output/console_writer'
require './lib/page_performance/output/file_writer'

